Getting Started from Source
---------------------------

Project Overlord consists of a repository (S-RAMP), Design Time Governance (DTGov) and Run Time Governance (RTGov).
This script will build S-RAMP and DTGov. Both of these projects have a GUI component. All components share login 
information using SAML bearer tokens. The SSO code lives in a shared project called overlord-commons. Because of
these SSO complexities we currently support deploying to JBossEAP and Tomcat-7.

1. Check out the code from Governance on Github
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This clones overlord-commons, s-ramp and dtgov from github. If you want to check out your own clones, then you can
update the urls in the build.properties file.
....
ant clone
....
going forward you can update using _ant pull_.

2. Download EAP 6.1.0 Final
~~~~~~~~~~~~~~~~~~~~~~~~~~~
You can skip this step if you're going to deploy on tomcat.
Navigate to http://www.jboss.org/jbossas/downloads then login and download EAP 6.1.0 Final (jboss-eap-6.1.0.zip) to this directory.

3. Build
~~~~~~~~
While your download is running you can kick off the build
....
ant install
....

4. Deploy
~~~~~~~~~

Option 1. Deploy to JBossEAP

When both step 2 and 3 are finished you can deploy to JBossEAP by running
....
ant deploy-eap
....

When ready, start EAP in standalone mode (jboss-eap-6.1/bin/standalone.sh) using a different shell

Option 2. Deploy to Tomcat

When step 2 is finished you can deploy to Tomcat by running
....
ant deploy-tomcat
....

When ready, start Tomcat (apache-tomcat-<version>/bin/start.sh) using a different shell

5. Seed
~~~~~~~
You can now add the following section to your .m2/settings.xml
....
<server>
   <id>local-sramp-repo-snapshots</id>
   <username>admin</username>
   <password>your-admin-password</password>
</server>
<server>
   <id>local-sramp-repo-snapshots</id>
   <username>admin</username>
   <password>your-admin-password</password>
</server>
....
Insert the admin password you supplied during step 4.

Make sure the applications are fully booted up before you start the seeding
....
ant seed
....
This will upload the ontologies as well as the workflows. You can verify
success using the s-ramp-ui. Demos for both S-RAMP and DTGov are available in 
their respective distribution directories.

Good luck!

Please use the overlord user forum if you need help or have any other questions.
We hope you will become part of our community and start writing your own
extensions. Looking forward to seeing some good Git pull requests.

Cheers,

The Overlord team.

.Other useful getting started links:
* http://www.jboss.org/overlord/
* https://github.com/Governance/s-ramp/wiki/GuideGettingStarted
* https://github.com/Governance/dtgov/wiki/GuideGettingStarted

